# -*- coding: utf-8 -*-
"""aml_fraud_detection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KqlRtN_gR9z81s5vH4jk86rYGzChILup
"""

import pandas as pd
from sklearn.cluster import DBSCAN
import numpy as np
import networkx as nx
import matplotlib.pyplot as plt

# Step 1: Load the dataset
data = {
    "customer_id": [1, 2, 1, 3, 2],
    "transaction_id": ["T001", "T002", "T003", "T004", "T005"],
    "transaction_date": ["2023-01-01", "2023-01-02", "2023-01-03", "2023-01-04", "2023-01-05"],
    "amount": [12000, 15000, 25000, 8000, 17000],
    "transaction_type": ["wire", "cash", "wire", "cash", "wire"],
    "country": ["US", "US", "Cayman Islands", "US", "Cayman Islands"]
}

# Create a DataFrame from the dataset
df = pd.DataFrame(data)

# Step 2: SQL Agent - Filter transactions exceeding $10,000
filtered_df = df[df["amount"] > 10000]
print("Filtered Transactions:")
print(filtered_df)

# Step 3: Rule-Based Agent - Apply AML rules
high_risk_countries = ["Cayman Islands", "Panama", "Switzerland"]
filtered_df["red_flag"] = (filtered_df["amount"] > 15000) | (filtered_df["country"].isin(high_risk_countries))
flagged_transactions = filtered_df[filtered_df["red_flag"]]
print("\nFlagged Transactions:")
print(flagged_transactions)

# Step 4: Machine Learning Agent - Detect anomalies using DBSCAN
transaction_amounts = np.array(flagged_transactions["amount"]).reshape(-1, 1)
dbscan = DBSCAN(eps=5000, min_samples=2).fit(transaction_amounts)
flagged_transactions["cluster"] = dbscan.labels_
anomalies = flagged_transactions[flagged_transactions["cluster"] == -1]
print("\nAnomalies Detected:")
print(anomalies)

# Step 5: Visualization Agent - Create a transaction network graph
G = nx.DiGraph()

# Add edges for flagged transactions (example data)
edges = [("Customer_1", "Bank_A"), ("Customer_2", "Bank_B"), ("Customer_1", "Bank_C")]
G.add_edges_from(edges)

# Draw the graph
plt.figure(figsize=(8, 6))
nx.draw(G, with_labels=True, node_color='lightblue', font_size=10, font_weight="bold")
plt.title("Suspicious Transaction Network")
plt.show()

